---
- hosts: jenkins-slave
  become: true
  tasks:
  - name: update ubuntu repo and cache
    apt:
      update_cache: yes
      force_apt_get: yes
      cache_valid_time: 3600
  - name: install java
    apt:
     name: openjdk-11-jre
     state: present
  - name: download maven package
    get_url: https://dlcdn.apache.org/mave/maven-3/3.9.4/binaries/apache-maven-3.9.4
    dest: /opt
  - name: extract maven packages
    unarchive: 
       src: /opt/apache-maven-3.9.4-bin.tar.gz
       dest: /opt
       remote_src: yes
